<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class PackageTemplateExport implements FromCollection, WithHeadings
{
  public function headings(): array
  {
    return [
      'Title (EN) *',
      'Title (AR) *',
      'Short Description (EN)',
      'Short Description (AR)',
      'Full Description (EN)',
      'Full Description (AR)',
      'Price *',
      'Original Price',
      'Discount %',
      'Duration (Nights) *',
      'Type *',
      'Destination (Name EN) *',
      'Min People',
      'Max People',
      'Distance from Center (km)',
      'Difficulty Level',
      'Best Season',
      'Is Featured (1/0)',
      'Is Offer (1/0)',
      'Offer Tag',
      'Is Popular (1/0)',
      'Rating',
      'Is Active (1/0)',
      'Inclusions (EN) - Comma separated',
      'Inclusions (AR) - Comma separated',
      'Exclusions (EN) - Comma separated',
      'Exclusions (AR) - Comma separated',
      'Day 1 Title (EN)',
      'Day 1 Activities (EN)',
      'Day 1 Title (AR)',
      'Day 1 Activities (AR)',
      'Day 2 Title (EN)',
      'Day 2 Activities (EN)',
      'Day 2 Title (AR)',
      'Day 2 Activities (AR)',
      'Day 3 Title (EN)',
      'Day 3 Activities (EN)',
      'Day 3 Title (AR)',
      'Day 3 Activities (AR)',
      'Day 4 Title (EN)',
      'Day 4 Activities (EN)',
      'Day 4 Title (AR)',
      'Day 4 Activities (AR)',
      'Day 5 Title (EN)',
      'Day 5 Activities (EN)',
      'Day 5 Title (AR)',
      'Day 5 Activities (AR)',
    ];
  }

  public function collection()
  {
    return collect([
      // Row 1: Guidance
      [
        'MANDATORY',
        'MANDATORY',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'MANDATORY',
        'OPTIONAL',
        'OPTIONAL',
        'MANDATORY',
        'MANDATORY',
        'MANDATORY',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
        'OPTIONAL',
      ],
      // Row 2: Valid Example (Destination exists in DB)
      [
        'Valid Package Example',
        'مثال لباقة صحيحة',
        'Destinations like Dubai exist.',
        'وجهات مثل دبي موجودة.',
        'This will be imported successfully.',
        'هذا سيتم رفعه بنجاح.',
        '1000',
        '1200',
        '20',
        '5',
        'Adventure',
        'Dubai',
        '1',
        '20',
        '1.0',
        'Moderate',
        'Winter',
        '1',
        '1',
        'Hot Deal',
        '1',
        '5',
        '1',
        'Flights, Hotel',
        'طيران, فندق',
        'Lunch',
        'الغداء',
        'Arrival',
        'Pick up from airport',
        'الوصول',
        'الاستقبال من المطار',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      ],
      // Row 3: Invalid Example (Destination DOES NOT exist in DB)
      [
        'Invalid Package Example',
        'مثال لباقة خاطئة',
        'Destination Mars does not exist.',
        'وجهة المريخ غير موجودة.',
        'This row will be skipped by the system.',
        'هذا السطر سيتم تجاهله من السيستم.',
        '9999',
        '',
        '',
        '99',
        'Space',
        'Mars',
        '1',
        '2',
        '999999',
        'Extreme',
        'Year-round',
        '0',
        '0',
        '',
        '0',
        '1',
        '1',
        'Space Suit',
        'بدلة فضاء',
        'Oxygen',
        'أوكسجين',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      ],
    ]);
  }
}
